branches:
  only:
    - master
    - /^.*travis.*$/
    - /^greenkeeper/.*$/

  except:
    - /^v\d+\.\d+\.\d+$/

sudo: required
dist: trusty
group: deprecated-2017Q4

language: node_js
node_js:
  - '9'
  - '8'
  - '6'
  - '10'

addons:
  apt:
    sources:
      - sourceline: 'deb https://debian.neo4j.org/repo stable/'
        key_url: 'https://debian.neo4j.org/neotechnology.gpg.key'
    packages:
      - neo4j

services:
  - mongodb

cache:
  directories:
    - ~/.npm

notifications:
  email: false

before_script:
  - sleep 15

script:
  - npm run test-travis

after_success:
  - npm run travis-deploy-once "npm run semantic-release && npm run coveralls"
